DDTAF_LITE Firefox_CaptureMainMenuItems.csv
DDTAF_LITE Firefox_OpenOptionsDlg.csv
DDTAF_LITE Firefox_CaptureOptionsGeneralTab.csv
DDTAF_LITE Firefox_CaptureOptionsGeneralTab2.csv
DDTAF_LITE Firefox_CaptureOptionsGeneralTab3.csv
DDTAF_LITE Firefox_CaptureOptionsGeneralTab4.csv

